name: Test

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4.1.7
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
      - name: Setup Node
        uses: actions/setup-node@v4.0.3
        with:
          node-version-file: .nvmrc
          cache: "pnpm"
      - name: Install Packages
        run: pnpm install --frozen-lockfile
      - name: Run Lint
        run: pnpm lint
      - name: Run Build
        run: pnpm build
